In [1]:
import numpy as np
from numpy import linalg as LA
from Func import *


In [58]:
# Forming N+1 particle subspace
params_Nplus1 = ParamModel(Num_level = 4, Delta = 1.0, Num_part = 2, Scat_ampl = 1.0)

basis_Nplus1, eigen_vectors_Nplus1 = SubspaceInfo(params_Nplus1, verbose_states = True, verbose_matrix = True)
print("Basis vectors with corresponding energy:")
print(basis_Nplus1)
print("Number of basis vectors:")
print(len(basis_Nplus1))
print("Eigen vectors of Hamiltonian matrix:")
print(eigen_vectors_Nplus1)

Ground state vector:
[1, 1, 0, 0]
List of all states:
[(1, 1, 0, 0), (1, 0, 1, 0), (0, 1, 1, 0), (1, 0, 0, 1), (0, 1, 0, 1), (0, 0, 1, 1)]
Number of all states
6
Final list of all states written as integers with corresponding kinetic energy:
[[1.0, 12], [2.0, 10], [3.0, 6], [3.0, 9], [4.0, 5], [5.0, 3]]
Sorted final list:
[[1.0, 12], [2.0, 10], [3.0, 6], [3.0, 9], [4.0, 5], [5.0, 3]]
List of all nonzero scattering elements:
[[0, 3, 1, 2], [1, 2, 0, 3]]
  0   1   2   3   4   5
0 1.0 0.0 0.0 0.0 0.0 0.0
1 0.0 2.0 0.0 0.0 0.0 0.0
2 0.0 0.0 3.0 -1.0 0.0 0.0
3 0.0 0.0 -1.0 3.0 0.0 0.0
4 0.0 0.0 0.0 0.0 4.0 0.0
5 0.0 0.0 0.0 0.0 0.0 5.0
Basis vectors with corresponding energy:
[[1.0, 12], [2.0, 10], [3.0, 6], [3.0, 9], [4.0, 5], [5.0, 3]]
Number of basis vectors:
6
Eigen vectors:
[[ 0.          0.          1.          0.          0.          0.        ]
 [ 0.          0.          0.          1.          0.          0.        ]
 [ 0.70710678  0.70710678  0.          0.          0.          0.

In [20]:
# Forming N particle subspace

params_N = ParamModel(Num_level = 4, Delta = 1.0, Num_part = 1, Scat_ampl = 1.0)

basis_N, eigen_vectors_N = SubspaceInfo(params_N, verbose_states = True, verbose_matrix = True)
print("Basis vectors with corresponding energy:")
print(basis_N)
print("Number of basis vectors:")
print(len(basis_N))
print("Eigen vectors of Hamiltonian matrix:")
print(eigen_vectors_N)

Ground state vector:
[1, 0, 0, 0]
List of all states:
[(1, 0, 0, 0), (0, 1, 0, 0), (0, 0, 1, 0), (0, 0, 0, 1)]
Number of all states
4
Final list of all states written as integers with corresponding kinetic energy:
[[0.0, 8], [1.0, 4], [2.0, 2], [3.0, 1]]
Sorted final list:
[[0.0, 8], [1.0, 4], [2.0, 2], [3.0, 1]]
List of all nonzero scattering elements:
[[0, 3, 1, 2], [1, 2, 0, 3]]
  0   1   2   3
0 0.0 0.0 0.0 0.0
1 0.0 1.0 0.0 0.0
2 0.0 0.0 2.0 0.0
3 0.0 0.0 0.0 3.0
[[0.0, 8], [1.0, 4], [2.0, 2], [3.0, 1]]
4
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [56]:
def MasterEquationPrep(basis_Nplus1, eigen_vectors_Nplus1, params, basis_N, eigen_vectors_N, verbose = True):
    '''
    This function calculates A_{ij} = \sum_{m=0}^{M-1}<\phi_i|\hat{c}_m|\psi_j> for given N and N+1.
    '''   
    
    print("N= ", params.Num_part -1, "N+1= ", params.Num_part) 

    for index_state_left in range(len(basis_N)): # marks number for the left state
        for index_state_right in range(len(basis_Nplus1)): # marks number for the right state
            sum_total = 0
            for index in range(params.Num_level): # marks index for annihilation operator \hat{c}_index
                  
                ket_vector_Nplus1 = Eigen_vector_ket(basis_Nplus1, eigen_vectors_Nplus1, index_state_right)        
                ket_vector_final = Kill_Eigen_State(ket_vector_Nplus1, params, index)
                
                # The complex conjugation in the left bra vector is not considered here,
                # because all elements of eigen states are choosen to be real.
                ket_vector_N = Eigen_vector_ket(basis_N, eigen_vectors_N, index_state_left) 

                # Now we can calculate <phi_{index_state_left}|c_index|phi_{index_state_right}>
                scal_prod = 0
                for i in range (len(ket_vector_N)):
                    for j in range (len(ket_vector_Nplus1)):
                        if(ket_vector_N[i][1] == ket_vector_final[j][1]):
                            scal_prod += ket_vector_N[i][0]*ket_vector_final[j][0]
                        #print('scal_prod', scal_prod)
                sum_total += scal_prod

                if(verbose == True):                    
                    print("index= ", index, "index_state_left= ", index_state_left, "index_state_right= ", index_state_right)
                    print(ket_vector_N)
                    print(ket_vector_Nplus1)
                    print(ket_vector_final)    
                    print("scal_prod= ", scal_prod)
            print("i= ", index_state_left, "j=", index_state_right, sum_total)


In [57]:
MasterEquationPrep(basis_Nplus1, eigen_vectors_Nplus1, params_Nplus1, basis_N, eigen_vectors_N, verbose = False)

N=  1 N+1=  2
i=  0 j= 0 0.707106781187
i=  0 j= 1 -0.707106781187
i=  0 j= 2 -1.0
i=  0 j= 3 -1.0
i=  0 j= 4 0.0
i=  0 j= 5 0.0
i=  1 j= 0 -0.707106781187
i=  1 j= 1 -0.707106781187
i=  1 j= 2 1.0
i=  1 j= 3 0.0
i=  1 j= 4 -1.0
i=  1 j= 5 0.0
i=  2 j= 0 0.707106781187
i=  2 j= 1 0.707106781187
i=  2 j= 2 0.0
i=  2 j= 3 1.0
i=  2 j= 4 0.0
i=  2 j= 5 -1.0
i=  3 j= 0 -0.707106781187
i=  3 j= 1 0.707106781187
i=  3 j= 2 0.0
i=  3 j= 3 0.0
i=  3 j= 4 1.0
i=  3 j= 5 1.0


In [9]:
# Some unit test

import unittest
from tests import *
suite = unittest.TestLoader().loadTestsFromTestCase(TestGround_State)
unittest.TextTestRunner(verbosity=2).run(suite)

suite = unittest.TestLoader().loadTestsFromTestCase(TestTo_integer)
unittest.TextTestRunner(verbosity=2).run(suite)

suite = unittest.TestLoader().loadTestsFromTestCase(TestKillState)
unittest.TextTestRunner(verbosity=2).run(suite)

suite = unittest.TestLoader().loadTestsFromTestCase(TestCreateState)
unittest.TextTestRunner(verbosity=2).run(suite)


test_6_5 (tests.TestGround_State) ... ok
test_6_6 (tests.TestGround_State) ... ok
test_error_negative (tests.TestGround_State) ... ok
test_error_smaller (tests.TestGround_State) ... ok

----------------------------------------------------------------------
Ran 4 tests in 0.019s

OK
test_7 (tests.TestTo_integer) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.006s

OK
test_4 (tests.TestKillState) ... ok
test_negative_numbers (tests.TestKillState) ... ok
test_too_big_index (tests.TestKillState) ... ok

----------------------------------------------------------------------
Ran 3 tests in 0.014s

OK
test_12 (tests.TestCreateState) ... ok
test_negative_numbers (tests.TestCreateState) ... ok
test_too_big_index (tests.TestCreateState) ... ok

----------------------------------------------------------------------
Ran 3 tests in 0.008s

OK


<unittest.runner.TextTestResult run=3 errors=0 failures=0>