In [1]:
import numpy as np
from Func import *

In [2]:
Num_level = 4
Num_part = 2
Delta = 1.0
scat_ampl = 1.0

In [3]:
v_ground = Ground_State(Num_level, Num_part)
print("Ground state vector:")
print(v_ground)
state_list = list(perm_unique(v_ground))
print("List of all exited states:")
print(state_list)
final_list = Final_list_create(state_list, Delta)
print("Final list of all exited states written as integers with corresponding kinetic energy:")
print(final_list)
final_list_sorted = sorted(final_list, key=getKey)
print("Sorted final list:")
print(final_list_sorted)

scat_elem = Find_Scat_Elem(Num_level)
print("List of all nonzero scattering elements:")
print(scat_elem)


Ground state vector:
[1, 1, 0, 0]
List of all exited states:
[(1, 1, 0, 0), (1, 0, 1, 0), (0, 1, 1, 0), (1, 0, 0, 1), (0, 1, 0, 1), (0, 0, 1, 1)]
Final list of all exited states written as integers with corresponding kinetic energy:
[[1.0, 12], [2.0, 10], [3.0, 6], [3.0, 9], [4.0, 5], [5.0, 3]]
Sorted final list:
[[1.0, 12], [2.0, 10], [3.0, 6], [3.0, 9], [4.0, 5], [5.0, 3]]
List of all nonzero scattering elements:
[[0, 3, 1, 2], [1, 2, 0, 3]]


In [4]:
print("Matrix representation of Hamiltonian:")
myMatrix = Fill_myMatrix(scat_elem, final_list_sorted, Num_level, scat_ampl)

Matrix representation of Hamiltonian:
  0   1   2   3   4   5
0 1.0 0.0 0.0 0.0 0.0 0.0
1 0.0 2.0 0.0 0.0 0.0 0.0
2 0.0 0.0 3.0 1.0 0.0 0.0
3 0.0 0.0 1.0 3.0 0.0 0.0
4 0.0 0.0 0.0 0.0 4.0 0.0
5 0.0 0.0 0.0 0.0 0.0 5.0


In [5]:
#Diagonalization of Hamiltonian
from numpy import linalg as LA

w, v = LA.eig(myMatrix)

print("Eigen values: ")
print(w)
print("Eigen vectors:")
print(v)
printMatrix(v)

Eigen values: 
[ 4.  2.  1.  2.  4.  5.]
Eigen vectors:
[[ 0.          0.          1.          0.          0.          0.        ]
 [ 0.          0.          0.          1.          0.          0.        ]
 [ 0.70710678 -0.70710678  0.          0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          1.          0.        ]
 [ 0.          0.          0.          0.          0.          1.        ]]
  0   1   2   3   4   5
0 0.0 0.0 1.0 0.0 0.0 0.0
1 0.0 0.0 0.0 1.0 0.0 0.0
2 0.707106781187 -0.707106781187 0.0 0.0 0.0 0.0
3 0.707106781187 0.707106781187 0.0 0.0 0.0 0.0
4 0.0 0.0 0.0 0.0 1.0 0.0
5 0.0 0.0 0.0 0.0 0.0 1.0


In [6]:
# Tests of matrix diagonalization
m = (v.dot(np.diag(w).dot(v.T))) # M = V W V^T, .dot is the matrix multiplication
print(m)
vect = v[:,1] # Eigen vectors are the coulumns of v
print(m.dot(vect))
print(vect)
print(m.dot(vect)/vect)

[[ 1.  0.  0.  0.  0.  0.]
 [ 0.  2.  0.  0.  0.  0.]
 [ 0.  0.  3.  1.  0.  0.]
 [ 0.  0.  1.  3.  0.  0.]
 [ 0.  0.  0.  0.  4.  0.]
 [ 0.  0.  0.  0.  0.  5.]]
[ 0.          0.         -1.41421356  1.41421356  0.          0.        ]
[ 0.          0.         -0.70710678  0.70710678  0.          0.        ]
[ nan  nan   2.   2.  nan  nan]


/home/natalia/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:7: RuntimeWarning: invalid value encountered in true_divide


In [10]:
import unittest
from tests import *
suite = unittest.TestLoader().loadTestsFromTestCase(TestGround_State)
unittest.TextTestRunner(verbosity=2).run(suite)

suite = unittest.TestLoader().loadTestsFromTestCase(TestTo_integer)
unittest.TextTestRunner(verbosity=2).run(suite)

suite = unittest.TestLoader().loadTestsFromTestCase(TestKillState)
unittest.TextTestRunner(verbosity=2).run(suite)

suite = unittest.TestLoader().loadTestsFromTestCase(TestCreateState)
unittest.TextTestRunner(verbosity=2).run(suite)


test_6_5 (tests.TestGround_State) ... ok
test_6_6 (tests.TestGround_State) ... ok
test_error_negative (tests.TestGround_State) ... ok
test_error_smaller (tests.TestGround_State) ... ok

----------------------------------------------------------------------
Ran 4 tests in 0.017s

OK
test_7 (tests.TestTo_integer) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.004s

OK
test_4 (tests.TestKillState) ... ok
test_negative_numbers (tests.TestKillState) ... ok
test_too_big_index (tests.TestKillState) ... ok

----------------------------------------------------------------------
Ran 3 tests in 0.013s

OK
test_12 (tests.TestCreateState) ... ok
test_negative_numbers (tests.TestCreateState) ... ok
test_too_big_index (tests.TestCreateState) ... ok

----------------------------------------------------------------------
Ran 3 tests in 0.021s

OK


<unittest.runner.TextTestResult run=3 errors=0 failures=0>